xaf/qolsysgw

- README.md
This was surprising to me, given I filed #14 and how I typically use "Arm Away" from my phone. Figured it'd be worth calling out in the docs.
> Clarify panel behavior with exit delay configured

- README.md
- apps/qolsysgw/qolsys/actions.py
- apps/qolsysgw/qolsys/config.py
- apps/qolsysgw/qolsys/control.py
- tests/integration/test_gateway_control.py
This new parameter allows to define what delay will be used when arming the alarm in ARM_STAY mode, if we want to override the configuration of the panel.
Fixes #5
> Add support for `arm_stay_exit_delay` parameter

- apps/qolsysgw/gateway.py
- apps/qolsysgw/mqtt/exceptions.py
- tests/integration/test_gateway.py
- tests/integration/test_gateway_control.py
- tests/mock_modules/appdaemon/plugins/mqtt/mqttapi.py
If the MQTT Plugin is not properly configured in appdaemon.yaml, the call to get_plugin_config will return None, which was not failing right away but later on when trying to send partition and sensor information to MQTT. This makes it fail earlier, with a clearer error message as an exception.
Fixes #10
> Show a better error message if missing `mqtt_plugin_cfg`

- apps/qolsysgw/gateway.py
- apps/qolsysgw/qolsys/events.py
- docs/qolsys-panel-interactions.md
- tests/integration/test_qolsys_events.py
At the moment, those events are simply ignored gracefully, and shown as an `INFO` message in the logs.
Fixes #37
> Add support for `ERROR` events

- apps/qolsysgw/qolsys/config.py
- apps/qolsysgw/qolsys/control.py
- docs/qolsys-panel-interactions.md
- tests/integration/test_alarm_control_panel_config.py
If the user code is specified in the YAML configuration as an all-digit value without quotes, it is parsed as an integer, except that we expect to work on a string. This fixes that by making sure that as long as the value we read is not empty, we make sure we will store it as a string.
Fixes #38
> Fix issue with the user code format

- .github/workflows/build.yaml
- .github/workflows/scripts/release.py
- README.md
- hacs.json
- info.md
> [ci] add release process and info.md file for HACS

- .github/workflows/build.yaml
With the branch being protected, using a `COMMIT_TOKEN` will allow the github action to commit changelog updates.
> [ci] use a commit token for changelog updates

- .github/workflows/scripts/release.py
- apps/qolsysgw/qolsys/config.py
- apps/qolsysgw/qolsys/control.py
The ARM control classes were sharing the same structure since the `exit_delay` support was added for `ARM_STAY`.
We can thus avoid deduplicating code by moving that logic to the parent class.
> ♻️ [refactor] deduplicate code in the ARM control classes

- README.md
- apps/qolsysgw/qolsys/actions.py
- apps/qolsysgw/qolsys/config.py
- apps/qolsysgw/qolsys/control.py
- docs/qolsys-panel-interactions.md
- tests/integration/test_gateway_control.py
The `ARMING` action of the panel does support a `bypass` parameter which allows to bypass the open sensors when arming. This introduces the support for that parameter in the configuration, as well as the ability to use the `ARM_CUSTOM_BYPASS` service in Home Assistant to arm with the `bypass` enabled.
Fixes #57
> ✨ [feature] Add support for `bypass` parameter when arming

- apps/qolsysgw/qolsys/control.py
- tests/integration/test_gateway_control.py
We had support for overriding `delay` and `bypass` when receiving a control command, which could be done in an Home Assistant automation for instance to have more control over what `qolsysgw` supports but that might not be exposable directly to Home Assistant. However, the parameters received from the control command were never read, and thus simply ignored. This fixes that.
> 🐛 [bugfix] Control commands weren't reading the `delay` and `bypass` parameters

- apps/qolsysgw/mqtt/updater.py
- apps/qolsysgw/qolsys/config.py
This would allow to reach situations with weird bugs as we could go around the `_SENTINEL` object by setting a value to `None`, which wouldn't be validated during the config `check` step.
> 🐛 [bugfix] config parameters shouldn't be overriden by 'None' values

- apps/qolsysgw/mqtt/updater.py
The device payload allows to link all of our entities to a unique device in Home Assistant. So far, we were generating the payload distinctly in every payload configuration. With this change, we put that device payload on a method to ensure that this payload stays identical across entities.
> ♻️ [refactor] centralize the generation of the device payload

- README.md
- apps/qolsysgw/mqtt/updater.py
- apps/qolsysgw/qolsys/config.py
- apps/qolsysgw/qolsys/sensors.py
- tests/end-to-end/fixtures/appdaemon/apps/apps.yaml.jinja
- tests/integration/test_qolsys_events.py
- tests/unit/qolsysgw/mqtt/test_updater.py
Entities such as 'bluetooth' devices are declared as sensors but do not seem to receive updates from the panel after that. We can thus simply disable those by default, allowing people that want to see them to enable them on a sensor-by-sensor basis, or even enable all of them thanks to a new configuration option
`enable_static_sensors_by_default` that can be set to `true`.
Fixes #67
> ✨ [feature] disable by default entities that do not update

- apps/qolsysgw/qolsys/sensors.py
- docs/qolsys-panel-interactions.md
- tests/end-to-end/test_qolsysgw.py
- tests/integration/test_alarm_control_panel_config.py
- tests/integration/test_gateway.py
- tests/integration/test_qolsys_events.py
- tests/integration/testbase.py
This adds a `tampered` attribute to sensors indicating if the sensor is currently believed to be tampered with or not.
This is not 100% accurate as it depends on specific sets of events that the panel is sending in a given order, which allow to guess if a sensor is currently tampered or not. This should be taken with a huge grain of salt as, for instance, we do not have that information when getting the summary state for the sensors from the panel (and will be able to know a sensor was tampered when it won't be tampered anymore).
More details are available at https://github.com/XaF/qolsysgw/issues/73 as to the identified interactions and how they are implemented here.
Fixes #73
> ✨ [feature] Add support for tampered sensors

- apps/qolsysgw/qolsys/control.py
- tests/integration/test_gateway_control.py
The gateway was expecting a user code from Home Assistant as soon as a code was required for the action to be performed. However, when a panel code is defined in the gateway configuration, this code might not be required if not specifically required by the `code_*_required` flags. This fixes that.
Fixes #79
> 🐛 [bugfix] handle properly when to require a user code from HA

- README.md
- docs/qolsysgw-entities.md
Adding documentation about the entities that `qolsysgw` creates, including the provided attributes.
This also adds a small example as how to convert an entity attribute into a sensor in Home Assistant.
Closes #80
> ✏️ [docs] Add documentation about the entities created by `qolsysgw`

- apps/qolsysgw/mqtt/updater.py
- tests/integration/test_qolsys_events.py
- tests/unit/qolsysgw/mqtt/test_updater.py
> 🐛 [bugfix] change sensors unique IDs to be recognized upon reinstall

- .github/workflows/build.yaml
Since last update, AppDaemon has changed the way the Python version is presented in their Dockerfile. This fixes that and makes the tests fail if we're unable to fetch the Python version, as well as centralize getting the Python version when preparing the environment before running the tests.
> 👷 [ci] update grabbing python version from AppDaemon

- tests/end-to-end/test_qolsysgw.py
Trying to avoid end-to-end tests failing regularly.
> build: 👷 try fixing panel port for CI runs

- README.md
Current link appears to be no longer active on their site.
Closes #189
> updating hacs-install readme link
